/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni2_jni2 */

#ifndef _Included_jni2_jni2
#define _Included_jni2_jni2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni2_jni2
 * Method:    readFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni2_jni2_readFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
